//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Aerial.db.dal.WorkOrderEntry {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/WorkOrderEntry.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/WorkOrderEntry.xsd", IsNullable=false)]
    public partial class WorkOrderEntry {
        
        private ClockPunches[] clockPunchesField;
        
        private Fields[] fieldsField;
        
        private Completed completedField;
        
        private Environment environmentField;
        
        private string pilotNotesField;
        
        private System.DateTime[] loadsField;
        
        public WorkOrderEntry() {
            this.pilotNotesField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClockPunches")]
        public ClockPunches[] ClockPunches {
            get {
                return this.clockPunchesField;
            }
            set {
                this.clockPunchesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fields")]
        public Fields[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
        
        /// <remarks/>
        public Completed Completed {
            get {
                return this.completedField;
            }
            set {
                this.completedField = value;
            }
        }
        
        /// <remarks/>
        public Environment Environment {
            get {
                return this.environmentField;
            }
            set {
                this.environmentField = value;
            }
        }
        
        /// <remarks/>
        public string PilotNotes {
            get {
                return this.pilotNotesField;
            }
            set {
                this.pilotNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Loads")]
        public System.DateTime[] Loads {
            get {
                return this.loadsField;
            }
            set {
                this.loadsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/WorkOrderEntry.xsd")]
    public partial class ClockPunches {
        
        private RecordStamp stampField;
        
        private System.DateTime dateField;
        
        /// <remarks/>
        public RecordStamp Stamp {
            get {
                return this.stampField;
            }
            set {
                this.stampField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/WorkOrderEntry.xsd")]
    public partial class RecordStamp {
        
        private string pilotField;
        
        private System.DateTime dateRecordedField;
        
        public RecordStamp() {
            this.pilotField = "";
            this.dateRecordedField = new System.DateTime(599265900000000000);
        }
        
        /// <remarks/>
        public string Pilot {
            get {
                return this.pilotField;
            }
            set {
                this.pilotField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateRecorded {
            get {
                return this.dateRecordedField;
            }
            set {
                this.dateRecordedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/WorkOrderEntry.xsd")]
    public partial class Completed {
        
        private RecordStamp stampField;
        
        private bool completeField;
        
        public Completed() {
            this.completeField = false;
        }
        
        /// <remarks/>
        public RecordStamp Stamp {
            get {
                return this.stampField;
            }
            set {
                this.stampField = value;
            }
        }
        
        /// <remarks/>
        public bool Complete {
            get {
                return this.completeField;
            }
            set {
                this.completeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/WorkOrderEntry.xsd")]
    public partial class Environment {
        
        private int windSpeedField;
        
        private string windDirectionField;
        
        private int temperatureField;
        
        private RecordStamp stampField;
        
        /// <remarks/>
        public int WindSpeed {
            get {
                return this.windSpeedField;
            }
            set {
                this.windSpeedField = value;
            }
        }
        
        /// <remarks/>
        public string WindDirection {
            get {
                return this.windDirectionField;
            }
            set {
                this.windDirectionField = value;
            }
        }
        
        /// <remarks/>
        public int Temperature {
            get {
                return this.temperatureField;
            }
            set {
                this.temperatureField = value;
            }
        }
        
        /// <remarks/>
        public RecordStamp Stamp {
            get {
                return this.stampField;
            }
            set {
                this.stampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/WorkOrderEntry.xsd")]
    public partial class Fields {
        
        private RecordStamp stampField;
        
        private string nameField;
        
        private string latLongField;
        
        private bool completedField;
        
        private Environment environmentField;
        
        /// <remarks/>
        public RecordStamp Stamp {
            get {
                return this.stampField;
            }
            set {
                this.stampField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string LatLong {
            get {
                return this.latLongField;
            }
            set {
                this.latLongField = value;
            }
        }
        
        /// <remarks/>
        public bool Completed {
            get {
                return this.completedField;
            }
            set {
                this.completedField = value;
            }
        }
        
        /// <remarks/>
        public Environment Environment {
            get {
                return this.environmentField;
            }
            set {
                this.environmentField = value;
            }
        }
    }
}
